# Generated by Django 3.1.1 on 2020-09-09 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.artikel'),
        ),
    ]
