# Generated by Django 3.1.1 on 2020-09-09 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200909_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='artikel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.artikel'),
        ),
    ]
