# Generated by Django 3.1.1 on 2020-10-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200909_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='quiz.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='verb_inf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verbs', to='quiz.word'),
        ),
    ]
