# Generated by Django 3.1.1 on 2020-10-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20201014_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
