# Generated by Django 3.1.1 on 2021-01-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20201023_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
